name: Azure Pipelines
variables:
  python.version: '3.7.6'
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: myAgentPool
    steps:
    - task: CmdLine@2
      displayName: Install Newman
      inputs:
        script: 'sudo apt-get install -y npm'
        workingDirectory: $(System.DefaultWorkingDirectory)
    - task: CmdLine@2
      displayName: Run Regression Tests
      continueOnError: true
      inputs:
        script: 'newman run starterapis.json'
        workingDirectory: $(System.DefaultWorkingDirectory)