name: Azure Pipelines
variables:
  python.version: '3.7.6'
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: myAgentPool
    steps:
    - task: CmdLine@2
      displayName: Install Newman
      inputs:
        script: 'sudo npm install -g newman'
        workingDirectory: $(System.DefaultWorkingDirectory)
    - task: CmdLine@2
      displayName: Get Directory
      inputs:
        script: |
          echo  '$(System.DefaultWorkingDirectory)'
          dir
          dir subfoldername
    - task: CmdLine@2
      displayName: Run Regression Tests
      continueOnError: true
      inputs:
        script: 'newman run starterapis.json'
        workingDirectory: '/Lesson\ 2:\ Creating\ and\ Deploying\ Azure\ Cloud\ Infrastructure/Exercise:\ Automated\ Testing\ Task'